//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Blacklist(en) erfolgreich gespeichert ähnelt.
        /// </summary>
        internal static string BlacklistSavedCaption {
            get {
                return ResourceManager.GetString("BlacklistSavedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Blacklist(en) wurde(n) erfolgreich gespeichert ähnelt.
        /// </summary>
        internal static string BlacklistSavedTest {
            get {
                return ResourceManager.GetString("BlacklistSavedTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alle Dateien|*.* ähnelt.
        /// </summary>
        internal static string FilterAllFiles {
            get {
                return ResourceManager.GetString("FilterAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alle Dateien|*.png;*.bmp;*.jpg;*.jpeg|Png|*.png|Bitmap|*.bmp|Jpg|*.jpg|Jpeg|*.jpeg ähnelt.
        /// </summary>
        internal static string FilterImageFiles {
            get {
                return ResourceManager.GetString("FilterImageFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keine Datei(en) ausgewählt ähnelt.
        /// </summary>
        internal static string NoFileSelectedCaption {
            get {
                return ResourceManager.GetString("NoFileSelectedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es wurden keine Datei(en) ausgewählt ähnelt.
        /// </summary>
        internal static string NoFileSelectedText {
            get {
                return ResourceManager.GetString("NoFileSelectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kein Speicherort für das Bild ausgewählt ähnelt.
        /// </summary>
        internal static string NoImageSelectedCaption {
            get {
                return ResourceManager.GetString("NoImageSelectedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es wurde kein Speicherort für das Bild ausgewählt ähnelt.
        /// </summary>
        internal static string NoImageSelectedText {
            get {
                return ResourceManager.GetString("NoImageSelectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Word cloud erstellt ähnelt.
        /// </summary>
        internal static string WordCloudGeneratedCaption {
            get {
                return ResourceManager.GetString("WordCloudGeneratedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Word cloud wurde erfolgreich erstellt ähnelt.
        /// </summary>
        internal static string WordCloudGeneratedText {
            get {
                return ResourceManager.GetString("WordCloudGeneratedText", resourceCulture);
            }
        }
    }
}
